INSERT INTO TBL_PRODUCT(PRICE,PRODUCT_NAME) VALUES(1.231, 'Madeira');
INSERT INTO TBL_PRODUCT(PRICE,PRODUCT_NAME) VALUES(123.99, 'Borracha');
INSERT INTO TBL_PRODUCT(PRICE,PRODUCT_NAME) VALUES(13.99, 'Plastico');
INSERT INTO TBL_PRODUCT(PRICE,PRODUCT_NAME) VALUES(9.99, 'Maçã');